### ISSUE TITLE
two columns responses height

### ISSUE THREAD

**Issue by diana1357** [AskiaADX/StatementsOther#2]
Hi

When I select two columns the responses height is wrong, please see below and the qex attached:
![statementother](https://user-images.githubusercontent.com/20987595/39296560-27603680-4939-11e8-8119-f9afc88d5e5c.PNG)

[StatementOther.zip](https://github.com/AskiaADX/StatementsOther/files/1950451/StatementOther.zip)

**Comment by Djedj** [comment]
Hi Diana,

Should be fixed in v2.0.13

Thks and Best Regards

**Comment by diana1357** [comment]
thank you! looks good!
