### ISSUE TITLE
Other text

### ISSUE THREAD

**Issue by diana1357** [AskiaADX/StatementsOther#3]
Hi

There is an issue with clearing the Other text data when using this adc with MC questions.

If you follow this scenario:
Select the "Other" option & Type in something
Deslect the "Other" option
Now if you select "Other" once again the adc text box is empty and all looks fine.
However in the  interview data, the text you typed in still there.

You can see this in my completed interview data, where "StatementOther" has options 1 and 5 selected, but the data from "OtherS" has not been cleared:
![capture](https://user-images.githubusercontent.com/20987595/40071274-2f139b90-5868-11e8-8039-bae8935dbe82.PNG)

SC questions seem fine, the same issue does not occur. 

Thanks
Diana

**Comment by Djedj** [comment]
Hi Diana,

It should be fixed in v2.0.16.

Best Regards
