### ISSUE TITLE
SC with two open

### ISSUE THREAD

**Issue by diana1357** [AskiaADX/StatementsOther#4]
Hi

If I have a SC question with two or more "Other" responses, if I click on one of the "Other" responses, then click on another response, the "Other" box stays open.
This does not happen for MC questions.
Please see the print screen:
![statement_other](https://user-images.githubusercontent.com/20987595/46200724-45075d80-c30a-11e8-80c1-83dfba70052e.PNG)

**Comment by Djedj** [comment]
Hi Diane,

I just updated the adc to v2.0.19, can you test it and tell me if it's ok for you ?

Best Regards

**Comment by diana1357** [comment]
Looks good! thank you!
