### ISSUE TITLE
SC with two open text boxes

### ISSUE THREAD

**Issue by diana1357** [AskiaADX/StatementsOther#5]
Hi 

If I have a SC quesiton with two other responses if:

1. I select one of the open responses and type in something
2. then select the other open response and type in something 
3. the first open response gets unselected from screen, and on the screen its open text box is empty, but in the data, what I typed in for the first response still stays:

The data is fine if you select another response, that doesn't have an open text box. 
![open_01](https://user-images.githubusercontent.com/20987595/46613301-ce890d80-cb0a-11e8-8df5-234cda08f0c5.PNG)
![open_02](https://user-images.githubusercontent.com/20987595/46613308-d3e65800-cb0a-11e8-9737-b1da7867cc4d.PNG)

Thanks
Diana

**Comment by Djedj** [comment]
Hi Diana,

I just updated the adc to v2.0.20. Can you test it and tell us if it makes the trick ?

Best Regards

**Comment by diana1357** [comment]
Thank you, yes, it looks good!
