### ISSUE TITLE
mc with two other

### ISSUE THREAD

**Issue by diana1357** [AskiaADX/StatementsOther#6]
Hi

When I have two open boxes, if I click on the second "other" option the text box opens. If I click again to type, the box closes. If I don't click, I can start typing and everything is fine.
however, I think respondents will try to click on the open box to type.
For the first open box all works fine.

Thanks
Diana

**Comment by Djedj** [comment]
Hi Diana,

I just updated the adc to v2.0.22. Can you test (empty your cache before) and tell us if it makes the trick ?

Best Regards

**Comment by diana1357** [comment]
thank you - looks good!
